before_script:
  - echo "ssltools"

job_build:
  stage: build
  tags:
    - cloud
  script:
    - ./ci-run.sh https://treasury.srv.hq.mendix.net/artifactory/cloud-snapshot-local
  except:
    - master

job_master:
  stage: build
  tags:
    - cloud
  script:
    - ./ci-run.sh https://treasury.srv.hq.mendix.net/artifactory/cloud-release-local
  only:
    - master
